name: deploy Eapp-to-tomcat
on:
  push:
   branches: [ "main" ]
jobs:
  build:  
     runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: set up jdk17
       -uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
      -name: build with maven
      run: mvn -B package --file pom.xml
